## This is an example of a shell script that you can mount with execute permission.
## Add this script to the $PATH via devfile.yaml to run it as a regular command

### Usage if added to path: "gitazure clone <UrlOfGitRepo>"
### This is only needed for the legacy self hosted Team Foundation Server git since DevSpaces does not support auth to it regularly.
### This shell script is just a git wrapper.

kind: Secret
apiVersion: v1
metadata:
  name: gitazure-shell-script-as-command
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-access-mode: '0775'
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /home/user/gitazure
data:
  ## The gitazure value is the below shell script:
   ## #!/bin/bash
   ## PATToken=yourLegacyAzurePATToken
   ## Base64Token=$(echo -n ":$PATToken" | base64)
   ## git -c http.extraHeader="Authorization: Basic $Base64Token" "$@"
  gitazure: IyEvYmluL2Jhc2gKClBBVFRva2VuPXlvdXJMZWdhY3lBenVyZVBBVFRva2VuCgpCYXNlNjRUb2tlbj0kKGVjaG8gLW4gIjokUEFUVG9rZW4iIHwgYmFzZTY0KQpnaXQgLWMgaHR0cC5leHRyYUhlYWRlcj0iQXV0aG9yaXphdGlvbjogQmFzaWMgJEJhc2U2NFRva2VuIiAiJEAiCg==
type: Opaque
